package com.events.infrastructure.security;
import org.junit.jupiter.api.Test;
import static org.assertj.core.api.Assertions.assertThat;
class BCryptCompatibilityTest {
    @Test void aceptaHashGeneradoPorSpringSecurity() {
        var hasher=new BCryptPasswordHasherAdapter();
        // Fixture generated by Spring Security 6.2.4 BCryptPasswordEncoder(10).
        String legacy="$2a$10$6SopXBt9uSYPP2p/60eTeupFqGSWMhYrz2S/9vxSCBnGfEdizVUee";
        assertThat(hasher.matches("Secreta123",legacy)).isTrue();
        assertThat(hasher.matches("Incorrecta123",legacy)).isFalse();
        assertThat(hasher.matches("Secreta123",hasher.hash("Secreta123"))).isTrue();
    }
}
